### PR TITLE
Incorporated the new way of using Docker on Travis

### PR DESCRIPTION
**Pull request by huntc**

### CODE REVIEW

**Comment by huntc** [comment]
@edwardcallahan @markusjura @fsat Any ideas on how we can make this work?

**Comment by markusjura** [comment]
@huntc: Using the docker service from travis will not work. Tried the same today and it results into this error when running one of the sbt scripted tests:

```
[info] [error] Error response from daemon: Cannot start container 6988397e31eb8e768b0665c863e072a8e5147f5bbe32518a2ada7e04f95041da: Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
```

My understanding is that it is not possible with the travis docker service to start custom containers because the docker service itself binds to the port 5432.

**Comment by markusjura** [comment]
Fixed the failing builds on travis with this PR: https://github.com/typesafehub/sbt-conductr-sandbox/pull/70

The reason for the failing builds has been that travis upgraded the infrastructure. The new infrastructure doesn't have the network interface `venet0:0` anymore which we used to identify the host ip.

@huntc: Can we close this PR?

**Comment by huntc** [comment]
Sure

**Comment by huntc** [comment]
Lgtm

**Pull request closed without merging**
