### PR TITLE
Specify bintray repo in image name

### PR DESCRIPTION
**Pull request by edwardcallahan**
With https://github.com/typesafehub/conductr/pull/741 the sandbox and conductr-dev docker namespaces will match.

### CODE REVIEW

**Comment by markusjura** [comment]
@edwardcallahan To pull the docker image authentication is required:

```
[error] Pulling repository typesafe-docker-internal-docker.bintray.io/conductr/conductr-dev
[error] time="2015-08-11T21:13:57+02:00" level=fatal msg="Authentication is required."
```

I thought that `conductr-dev` should be free and therefor should not require authentication?

How can the user specify the auth credentials if he uses the docker image `typesafe-docker-internal-docker.bintray.io/conductr/conductr`?

**Comment by edwardcallahan** [comment]
The docker-internal repo itself is private. Our eventual goal is to proxy the repo. Users would only need a Typesafe.com account to auth with our docker proxy. 

Today, users can create a bintray account that we authorize and login to the bintray repo (docker login -u <USERNAME> -p <API_KEY> -e <EMAIL> typesafe-docker-internal-docker.bintray.io). 

For CI a .dockercfg with "https://typesafe-docker-internal-docker.bintray.io" object authenticates for pulls against the bintray private registry.

**Comment by huntc** [comment]
@edwardcallahan Please configure travis with credentials for accessing the repo as part of this PR.

**Comment by huntc** [comment]
Otherwise LGTM

**Comment by edwardcallahan** [comment]
Per http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests
"Pull requests sent from forked repositories don’t have this (secure) data available in their builds. All data that’s considered confidential will not be added to the build’s environment."

For validation that this does work as expected, see branch build:
https://travis-ci.org/typesafehub/sbt-conductr-sandbox/builds/75335670

**Comment by markusjura** [comment]
LGTM. Can we merge this?

**Comment by markusjura** [comment]
@edwardcallahan Does this mean that every PR build will fail in travis if the changes in the PR are made in a fork?

If so based on our current PR / fork approach every build will fail and the README of sbt-conductr-sandbox will always display the 'failed build' badge.

Any solution for this?

**Comment by huntc** [comment]
The solution is to publish conductr-dev to the public docker repo. I'm in negotiations. :-)

FYI Ed and I have been discussing this issue separately.

**Comment by markusjura** [comment]
Yes, that would be great :-)

**Pull request merged**
